/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Objects.*; 
import java.awt.Color;
import Utils.*;
/**
 *
 * @author 344179247
 */
public class App1 extends javax.swing.JFrame {
    private final static Option[] options = new Option[7];
    public static App app;
    /**
     * Creates new form App1
     */
    public App1() {
        initComponents();
        //Init location Options and Option Entries
        OptionEntry locationOn = new OptionEntry("On", 2.0, 20, "Multiplication", "Addition");
        OptionEntry locationOff = new OptionEntry ("Off", 0.0, 0.0, "Addition");
        options[0] = new Option ("Location", locationOn, locationOff);
        //init pictures
        OptionEntry picturesOn = new OptionEntry("On", 2.0, 2.0, "Multiplication");
        OptionEntry picturesOff = new OptionEntry("Off", 0.0, 0.0, "Addition");
        options[1] = new Option("Pictures", picturesOn, picturesOff);
        //init camera
        OptionEntry cameraOn = new OptionEntry("On", 1.5,1.1, "Multiplication");
        OptionEntry cameraOff = new OptionEntry("Off", 0.0, 0.0, "Addition");
        options[2] = new Option("Camera", cameraOn, cameraOff);
        //init banners
        OptionEntry bannerOn = new OptionEntry("On", 10.0, 5.0, "Addition");
        OptionEntry bannerOff = new OptionEntry("Off", 0.0, 0.0, "Addition");
        options[3] = new Option("Banner", bannerOn,bannerOff);
        //init newsletters
        OptionEntry newsLetterOn = new OptionEntry("On", 1.2, 1.0, "Multiplication","Multiplication");
        OptionEntry newsLetterOff = new OptionEntry("Off", 0.0, 0.0, "Addition");
        options[4] = new MaillingList("app1","NewsLetter", newsLetterOn, newsLetterOff);
        //init advertisements
        OptionEntry advertisementsOn = new OptionEntry("On", 2.0, 1.0, "Multiplication");
        OptionEntry advertisementsOff = new OptionEntry("Off", 0.0, 0.0,"Addition");
        options[5] = new Option("Advertisements",advertisementsOn, advertisementsOff);
        //init combo box
        OptionEntry everyone = new OptionEntry("Everyone", 2.5, 2.0, "Multiplication");
        OptionEntry onlyMe = new OptionEntry("Only Me", 0.0,0.0, "Addition");
        OptionEntry friends = new OptionEntry("Friends", 1.1,1.75,"Multiplication" );
        options[6] = new Option("posts",everyone,friends ,onlyMe);
        
        posts.addItem("Only Me");
        posts.addItem("Friends");
        posts.addItem("Everyone");
        
        app = new App("yz", options[0], options[1], options[2], options[3], options[4], options[5], options[6]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        privacySetting1 = new javax.swing.JToggleButton();
        privacySetting2 = new javax.swing.JToggleButton();
        privacySetting3 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        notificationSetting1 = new javax.swing.JToggleButton();
        notificationSetting2 = new javax.swing.JToggleButton();
        notificationSetting3 = new javax.swing.JToggleButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        posts = new javax.swing.JComboBox<>();
        privacySetting4 = new javax.swing.JToggleButton();
        privacySetting5 = new javax.swing.JToggleButton();
        privacySetting6 = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        notificationSetting4 = new javax.swing.JToggleButton();
        notificationSetting5 = new javax.swing.JToggleButton();
        notificationSetting6 = new javax.swing.JToggleButton();
        jLabel15 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setText("APP NAME ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        privacySetting1.setBackground(new java.awt.Color(153, 255, 153));
        privacySetting1.setSelected(true);
        privacySetting1.setText("On");
        privacySetting1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privacySetting1ActionPerformed(evt);
            }
        });

        privacySetting2.setBackground(new java.awt.Color(153, 255, 153));
        privacySetting2.setSelected(true);
        privacySetting2.setText("On");
        privacySetting2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privacySetting2ActionPerformed(evt);
            }
        });

        privacySetting3.setBackground(new java.awt.Color(153, 255, 153));
        privacySetting3.setSelected(true);
        privacySetting3.setText("On");

        jLabel2.setText("Setting 1");

        jLabel3.setText("Setting 2");

        jLabel4.setText("Setting 3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addComponent(privacySetting1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(privacySetting2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(privacySetting3, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(privacySetting1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(privacySetting2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(privacySetting3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Privacy", jPanel1);

        jLabel5.setText("Setting 1");

        jLabel6.setText("Setting 2");

        jLabel7.setText("Setting 3");

        notificationSetting1.setBackground(new java.awt.Color(153, 255, 153));
        notificationSetting1.setSelected(true);
        notificationSetting1.setText("On");
        notificationSetting1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationSetting1ActionPerformed(evt);
            }
        });

        notificationSetting2.setBackground(new java.awt.Color(153, 255, 153));
        notificationSetting2.setSelected(true);
        notificationSetting2.setText("On");
        notificationSetting2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationSetting2ActionPerformed(evt);
            }
        });

        notificationSetting3.setBackground(new java.awt.Color(153, 255, 153));
        notificationSetting3.setSelected(true);
        notificationSetting3.setText("On");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addComponent(notificationSetting3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(notificationSetting2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(notificationSetting1)))
                .addContainerGap())
            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(notificationSetting1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(notificationSetting2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(notificationSetting3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Notificaion", jPanel2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("YZ ");

        posts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postsActionPerformed(evt);
            }
        });

        privacySetting4.setBackground(new java.awt.Color(51, 255, 0));
        privacySetting4.setSelected(true);
        privacySetting4.setText("On");
        privacySetting4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privacySetting4ActionPerformed(evt);
            }
        });

        privacySetting5.setBackground(new java.awt.Color(51, 255, 0));
        privacySetting5.setSelected(true);
        privacySetting5.setText("On");
        privacySetting5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privacySetting5ActionPerformed(evt);
            }
        });

        privacySetting6.setBackground(new java.awt.Color(51, 255, 0));
        privacySetting6.setSelected(true);
        privacySetting6.setText("On");
        privacySetting6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privacySetting6ActionPerformed(evt);
            }
        });

        jLabel9.setText("Location");

        jLabel10.setText("Pictures");

        jLabel11.setText("Camera");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Who Has Access To Your Posts?");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(posts, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addComponent(privacySetting4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(privacySetting5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(privacySetting6, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(privacySetting4)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(privacySetting5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(privacySetting6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(4, 4, 4)
                .addComponent(posts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Privacy", jPanel3);

        jLabel12.setText("Banners");

        jLabel13.setText("Newsletters");

        notificationSetting4.setBackground(new java.awt.Color(51, 255, 0));
        notificationSetting4.setSelected(true);
        notificationSetting4.setText("On");
        notificationSetting4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationSetting4ActionPerformed(evt);
            }
        });

        notificationSetting5.setBackground(new java.awt.Color(51, 255, 0));
        notificationSetting5.setSelected(true);
        notificationSetting5.setText("On");
        notificationSetting5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationSetting5ActionPerformed(evt);
            }
        });

        notificationSetting6.setBackground(new java.awt.Color(51, 255, 0));
        notificationSetting6.setSelected(true);
        notificationSetting6.setText("On");
        notificationSetting6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationSetting6ActionPerformed(evt);
            }
        });

        jLabel15.setText("Advertisements");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                                .addComponent(notificationSetting5))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(notificationSetting4))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(notificationSetting6)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(notificationSetting4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(notificationSetting5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(notificationSetting6)
                    .addComponent(jLabel15))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Notificaion", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void privacySetting1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privacySetting1ActionPerformed
    }//GEN-LAST:event_privacySetting1ActionPerformed
    private void privacySetting2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privacySetting2ActionPerformed
    }//GEN-LAST:event_privacySetting2ActionPerformed
    private void notificationSetting1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationSetting1ActionPerformed
    }//GEN-LAST:event_notificationSetting1ActionPerformed
    private void notificationSetting2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationSetting2ActionPerformed
    }//GEN-LAST:event_notificationSetting2ActionPerformed
    private void privacySetting4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privacySetting4ActionPerformed
        //if the button is selected change the button to green and selected obj to On
        if (privacySetting4.isSelected()){
            options[0].SelectEntry("On"); 
            privacySetting4.setBackground(Color.green);
            privacySetting4.setText("On");
        }
        
        //if the button is not selected turn the button off and selected obj to off 
        if (!privacySetting4.isSelected()){
            options[0].SelectEntry("Off"); 
            privacySetting4.setBackground(Color.red);
            privacySetting4.setText("Off");
        }
    }//GEN-LAST:event_privacySetting4ActionPerformed
    private void privacySetting5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privacySetting5ActionPerformed
        //if the button is selected change the button to green and the selected obj to on
        if (privacySetting5.isSelected()){
            options[1].SelectEntry("On"); 
            privacySetting5.setBackground(Color.green);
            privacySetting5.setText("On");
        }
        
        //if the button is not selected turn the button off and selected obj to off
        if (!privacySetting5.isSelected()){
            options[1].SelectEntry("Off");
            privacySetting5.setBackground(Color.red);
            privacySetting5.setText("Off");
        }
    }//GEN-LAST:event_privacySetting5ActionPerformed

    private void notificationSetting4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationSetting4ActionPerformed
        //if the button is selected change the button to green and the selected obj to on
        if (notificationSetting4.isSelected()){
            options[3].SelectEntry("On"); 
            notificationSetting4.setBackground(Color.green);
            notificationSetting4.setText("On");
        }
        
        //if the button is not selected turn the button off and selected obj to off
        if (!notificationSetting4.isSelected()){
            options[3].SelectEntry("Off");
            notificationSetting4.setBackground(Color.red);
            notificationSetting4.setText("Off");
        }
    }//GEN-LAST:event_notificationSetting4ActionPerformed

    private void notificationSetting5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationSetting5ActionPerformed
        //if the button is selected change the button to green and the selected obj to on
        if (notificationSetting5.isSelected()){
            options[4].SelectEntry("On");
            notificationSetting5.setBackground(Color.green);
            notificationSetting5.setText("On");
        }
        
        //if the button is not selected turn the button off and selected obj to off
        if (!notificationSetting5.isSelected()){
            options[4].SelectEntry("Off");
            notificationSetting5.setBackground(Color.red);
            notificationSetting5.setText("Off");
        }
    }//GEN-LAST:event_notificationSetting5ActionPerformed

    private void notificationSetting6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationSetting6ActionPerformed
        //if the button is selected change the button to green and the selected obj to on
        if (notificationSetting6.isSelected()){
            options[5].SelectEntry("On");
            notificationSetting6.setBackground(Color.green);
            notificationSetting6.setText("On");
        }
        //if the button is not selected turn the button off and selected obj to off
        
        if (!notificationSetting6.isSelected()){
            options[5].SelectEntry("Off");
            notificationSetting6.setBackground(Color.red);
            notificationSetting6.setText("Off");
        }
    }//GEN-LAST:event_notificationSetting6ActionPerformed

    private void privacySetting6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privacySetting6ActionPerformed
        //if the button is selected change the button to green and the selected obj to on
        if (privacySetting6.isSelected()){
            options[2].SelectEntry("Off");
            privacySetting6.setBackground(Color.green);
            privacySetting6.setText("On");
        }
        //if the button is not selected turn the button off and selected obj to off
        
        if (!privacySetting6.isSelected()){
            options[2].SelectEntry("Off");
            privacySetting6.setBackground(Color.red);
            privacySetting6.setText("Off");
        }
    }//GEN-LAST:event_privacySetting6ActionPerformed

    private void postsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postsActionPerformed
        //gets the selected item from the combo box and turns it into the selected item for options[6]
        String x = (String) posts.getSelectedItem();
        options[6].SelectEntry(x);
    }//GEN-LAST:event_postsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToggleButton notificationSetting1;
    private javax.swing.JToggleButton notificationSetting2;
    private javax.swing.JToggleButton notificationSetting3;
    private javax.swing.JToggleButton notificationSetting4;
    private javax.swing.JToggleButton notificationSetting5;
    private javax.swing.JToggleButton notificationSetting6;
    private javax.swing.JComboBox<String> posts;
    private javax.swing.JToggleButton privacySetting1;
    private javax.swing.JToggleButton privacySetting2;
    private javax.swing.JToggleButton privacySetting3;
    private javax.swing.JToggleButton privacySetting4;
    private javax.swing.JToggleButton privacySetting5;
    private javax.swing.JToggleButton privacySetting6;
    // End of variables declaration//GEN-END:variables
}
