import java.awt.Color;
import Objects.*; 

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 344179247
 */
public class App3 extends javax.swing.JFrame {
    private static final Option [] options = new Option[7];
    public static App app;
    /**
     * Creates new form defaultSetting
     */
    public App3() {
        initComponents();
        //Init location Options and Option Entries
        OptionEntry locationOn = new OptionEntry("On", 2.0, 20, "Multiplication", "Addition");
        OptionEntry locationOff = new OptionEntry ("Off", 0.0, 0.0, "Addition");
        options[0] = new Option ("Location", locationOn, locationOff);
        //init pictures
        OptionEntry picturesOn = new OptionEntry("On", 2.0, 2.0, "Multiplication");
        OptionEntry picturesOff = new OptionEntry("Off", 0.0, 0.0, "Addition");
        options[1] = new Option("Pictures", picturesOn, picturesOff);
        //init camera
        OptionEntry cameraOn = new OptionEntry("On", 1.5,1.1, "Multiplication");
        OptionEntry cameraOff = new OptionEntry("Off", 0.0, 0.0, "Addition");
        options[2] = new Option("Camera", cameraOn, cameraOff);
        //init banners
        OptionEntry bannerOn = new OptionEntry("On", 10.0, 5.0, "Addition");
        OptionEntry bannerOff = new OptionEntry("Off", 0.0, 0.0, "Addition");
        options[3] = new Option("Banner", bannerOn,bannerOff);
        //init newsletters
        OptionEntry newsLetterOn = new OptionEntry("On", 1.2, 1.0, "Multiplication");
        OptionEntry newsLetterOff = new OptionEntry("Off", 0.0, 0.0, "Addition");
        options[4] = new Option("NewsLetter", newsLetterOn, newsLetterOff);
        //init advertisements
        OptionEntry advertisementsOn = new OptionEntry("On", 2.0, 1.0, "Multiplication");
        OptionEntry advertisementsOff = new OptionEntry("Off", 0.0, 0.0, "Addition");
        options[5] = new MaillingList("App3","Advertisements",advertisementsOn, advertisementsOff);
        //init the combo box
        OptionEntry everyone = new OptionEntry("Everyone", 2.5, 2.0, "Multiplication");
        OptionEntry onlyMe = new OptionEntry("Only Me", 0.0,0.0, "Addition");
        OptionEntry friends = new OptionEntry("Friends", 1.1,1.75,"Multiplication");
        options[6] = new Option("posts",everyone,friends ,onlyMe);
        posts.addItem("Only Me");
        posts.addItem("Friends");
        posts.addItem("Everyone");
        
        app = new App("FootBook", options[0], options[1], options[2], options[3], options[4], options[5], options[6]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        posts = new javax.swing.JComboBox<>();
        privacySetting1 = new javax.swing.JToggleButton();
        privacySetting2 = new javax.swing.JToggleButton();
        privacySetting3 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        notificationSetting1 = new javax.swing.JToggleButton();
        notificationSetting2 = new javax.swing.JToggleButton();
        notificationSetting3 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FootBook");

        posts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postsActionPerformed(evt);
            }
        });

        privacySetting1.setBackground(new java.awt.Color(51, 255, 0));
        privacySetting1.setSelected(true);
        privacySetting1.setText("On");
        privacySetting1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privacySetting1ActionPerformed(evt);
            }
        });

        privacySetting2.setBackground(new java.awt.Color(51, 255, 0));
        privacySetting2.setSelected(true);
        privacySetting2.setText("On");
        privacySetting2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privacySetting2ActionPerformed(evt);
            }
        });

        privacySetting3.setBackground(new java.awt.Color(51, 255, 0));
        privacySetting3.setSelected(true);
        privacySetting3.setText("On");
        privacySetting3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privacySetting3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Location");

        jLabel3.setText("Pictures");

        jLabel4.setText("Camera");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(posts, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addComponent(privacySetting1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(privacySetting2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(privacySetting3, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(privacySetting1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(privacySetting2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(privacySetting3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(posts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Privacy", jPanel1);

        jLabel5.setText("Banners ");

        jLabel6.setText("Newsletters");

        jLabel7.setText("Advertisements");

        notificationSetting1.setBackground(new java.awt.Color(51, 255, 0));
        notificationSetting1.setSelected(true);
        notificationSetting1.setText("On");
        notificationSetting1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationSetting1ActionPerformed(evt);
            }
        });

        notificationSetting2.setBackground(new java.awt.Color(51, 255, 0));
        notificationSetting2.setSelected(true);
        notificationSetting2.setText("On");
        notificationSetting2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationSetting2ActionPerformed(evt);
            }
        });

        notificationSetting3.setBackground(new java.awt.Color(51, 255, 0));
        notificationSetting3.setSelected(true);
        notificationSetting3.setText("On");
        notificationSetting3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationSetting3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addComponent(notificationSetting3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(notificationSetting2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(notificationSetting1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(notificationSetting1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(notificationSetting2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(notificationSetting3))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Notificaion", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void privacySetting1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privacySetting1ActionPerformed
        //if the button is selected change the button to green and selected obj to On
        if (privacySetting1.isSelected()){
            options[0].SelectEntry("On"); 
            privacySetting1.setBackground(Color.green);
            privacySetting1.setText("On");
        }
        
        //if the button is not selected turn the button off and selected obj to off 
        if (!privacySetting1.isSelected()){
            options[0].SelectEntry("Off"); 
            privacySetting1.setBackground(Color.red);
            privacySetting1.setText("Off");
        
        }
    }//GEN-LAST:event_privacySetting1ActionPerformed

    private void notificationSetting1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationSetting1ActionPerformed
        //if the button is selected change the button to green and selected obj to On
        if (notificationSetting1.isSelected()){
            options[3].SelectEntry("On"); 
            notificationSetting1.setBackground(Color.green);
            notificationSetting1.setText("On");
        }
        
        //if the button is not selected turn the button off and selected obj to off 
        if (!notificationSetting1.isSelected()){
            options[3].SelectEntry("Off");
            notificationSetting1.setBackground(Color.red);
            notificationSetting1.setText("Off");
        }
    }//GEN-LAST:event_notificationSetting1ActionPerformed

    private void privacySetting2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privacySetting2ActionPerformed
         //if the button is selected change the button to green and selected obj to On
        if (privacySetting2.isSelected()){
            options[1].SelectEntry("On"); 
            privacySetting2.setBackground(Color.green);
            privacySetting2.setText("On");
        }
        
        //if the button is not selected turn the button off and selected obj to off 
        if (!privacySetting2.isSelected()){
            options[1].SelectEntry("Off"); 
            privacySetting2.setBackground(Color.red);
            privacySetting2.setText("Off");
        }
    }//GEN-LAST:event_privacySetting2ActionPerformed

    private void notificationSetting2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationSetting2ActionPerformed
        //if the button is selected change the button to green and selected obj to On
        if (notificationSetting2.isSelected()){
            options[4].SelectEntry("On"); 
            notificationSetting2.setBackground(Color.green);
            notificationSetting2.setText("On");
        }
        
        //if the button is not selected turn the button off and selected obj to off 
        if (!notificationSetting2.isSelected()){
            options[4].SelectEntry("Off");
            notificationSetting2.setBackground(Color.red);
            notificationSetting2.setText("Off");
        }
    }//GEN-LAST:event_notificationSetting2ActionPerformed

    private void postsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postsActionPerformed
        // TODO add your handling code here:
        String x = (String) posts.getSelectedItem();
        options[6].SelectEntry(x);
        
        
        
    }//GEN-LAST:event_postsActionPerformed

    private void privacySetting3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privacySetting3ActionPerformed
        //if the button is selected change the button to green and selected obj to On
        if (privacySetting3.isSelected()){
            options[2].SelectEntry("On"); 
            privacySetting3.setBackground(Color.green);
            privacySetting3.setText("On");
        }
        
        //if the button is not selected turn the button off and selected obj to off 
        if (!privacySetting3.isSelected()){
            options[2].SelectEntry("Off");
            privacySetting3.setBackground(Color.red);
            privacySetting3.setText("Off");
        }
    }//GEN-LAST:event_privacySetting3ActionPerformed

    private void notificationSetting3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationSetting3ActionPerformed
        //if the button is selected change the button to green and selected obj to On
        if (notificationSetting3.isSelected()){
            options[5].SelectEntry("On"); 
            notificationSetting3.setBackground(Color.green);
            notificationSetting3.setText("On");
        }
        
        //if the button is not selected turn the button off and selected obj to off 
        if (!notificationSetting3.isSelected()){
            options[5].SelectEntry("Off");
            notificationSetting3.setBackground(Color.red);
            notificationSetting3.setText("Off");
        }




    }//GEN-LAST:event_notificationSetting3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton notificationSetting1;
    private javax.swing.JToggleButton notificationSetting2;
    private javax.swing.JToggleButton notificationSetting3;
    private javax.swing.JComboBox<String> posts;
    private javax.swing.JToggleButton privacySetting1;
    private javax.swing.JToggleButton privacySetting2;
    private javax.swing.JToggleButton privacySetting3;
    // End of variables declaration//GEN-END:variables
}
